applications:
- path: .
  memory: 256M
  instances: 1
  domain: mybluemix.net
  name: EnviosYa
  host: EnviosYa
  disk_quota: 1024M
  command: bundle exec rake db:setup && bundle exec rails s -p $PORT && rake db:migrate && bin/rails server -p $PORT -e $RAILS_ENV
  services:
  - enviosya