update_cost:
    cron: "*/10 * * * *"
    class: "UpdateCostJob"
    queue: default

send_mail:
    cron: "*/5 * * * *"
    class: "SendMailJob"
    queue: default

clear_log:
    cron: "0 0 3 1/1 * ? *"
    class: "ClearFile"
    queue: default